apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
  labels:
    app: amazon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: amazon-container
        image: henrykum23/amazon:latest
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 6
        #   timeoutSeconds: 1
        #   periodSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-service
spec:
  selector:
    app: amazon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazon-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amazon-service
                port:
                  number: 80